name: Publish NuGet Packages

on:
  release:
    types: [ published ]

jobs:
  publish_nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Node 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Publish NuGet package
      shell: pwsh
      run: Build/scripts/rest_api_client.publish.ps1 -version ${{github.ref_name}} -publshFolder Keycloak.RestApiClient.${{github.ref_name}} -nugetUrl https://api.nuget.org/v3/index.json -apiKey ${{ secrets.NUGET_API_KEY }} -openApiJson https://raw.githubusercontent.com/dahag-ag/keycloak-openapi/main/OpenApiDefinitions/keycloak-20.0.0.json